### ISSUE TITLE
Problem: there's no good desktop client for nostr

### ISSUE THREAD

**Issue by gsovereignty** [Stackerstan/interfarce#19]
I ran a poll in the Nostr group chat asking what to build next, and what the community wants the most is a good desktop client.

This would also be a way nicer way to interact with stackerstan.

Is there a way I can build this as a stackerstan project?

ping @stanstacks @bitkarrot @pqingshuang

**Comment by stanstacks** [comment]
Have a look in the Protocol for "dictatorial repository". 

But essentially, yes you should be able to build a nostr desktop client as part of this project. I'm not sure what the revenue model would be, but we can figure that out later.

I've been playing around with subscribing to all events from many relays and caching them locally so that they can be sliced and diced. There's a branch on my fork of the mindmachine, have a look at the *gnostr* scum-class mind. What you could consider doing is hooking into that or doing something similar and then rendering events using Wails (https://wails.io/docs/introduction)

**Comment by bitkarrot** [comment]
Desktop client for nostr much needed. Its difficult to figure out what is good right now, due to info saturation. there are multiple clients that can be found at https://www.nostr.net/ that might be worth taking a look at
